### ISSUE TITLE
api.refund(order, callback); 支持await吗？

### ISSUE THREAD

**Issue by longxianlin** [befinal/node-tenpay#10]

**Comment by longxianlin** [comment]
{ Error: mac verify failure, POST https://api.mch.weixin.qq.com/secapi/pay/refund -1 (connected: false, keepalive socket: false)

这个是什么错误呢？

**Comment by longxianlin** [comment]
const result = await api.refund(order);
会返回null

**Comment by longxianlin** [comment]
Error: mac verify failure检查了，是使用不正确的证书。

**Comment by befinal** [comment]
先检查证书，错误的情况下会直接抛出错误，如果用了await 注意使用try
