### ISSUE TITLE
修改了一点统一下单接口异步问题，新增了回调验签

### ISSUE THREAD

**Issue by Yumazhiyao** [befinal/node-tenpay#101]
成为开发者

**Comment by Yumazhiyao** [comment]
async checkNotifySign(params) {
    let xmlObj = await util.parseXML(params);
    this.log(xmlObj.appid, this.appid, xmlObj.mch_id, this.mchid, 'lll')
    if (xmlObj.appid !== this.appid) return false;
    if (xmlObj.mch_id !== this.mchid) return false;
    if (xmlObj.return_code !== 'SUCCESS') return false;
    let string = ''
    let keys = Object.keys(xmlObj)
    keys.sort()
    keys.forEach(key => {
      if (xmlObj[key] && key !== 'sign') {
        string = string + key + '=' + xmlObj[key] + '&'
      }
    })
    string = string + 'key=' + this.partnerKey;
    return util.md5(string).toUpperCase() === xmlObj.sign;
  }

  async getNotifyObj(params) {
    return await util.parseXML(params);
  }

**Comment by befinal** [comment]
回调本身就有验签功能，查询中间件相关代码
