### ISSUE TITLE
util中的decrpt方法是否调用错了？

### ISSUE THREAD

**Issue by pouringrain0628** [befinal/node-tenpay#103]
![image](https://user-images.githubusercontent.com/29463605/70694476-a989bf00-1cfa-11ea-9a6e-89ee1d0fbae9.png)
 let decoded = decipher.update(encryptedData, 'base64', 'utf8');
后两个参数的位置是否错了？

改为ts版本实现时发现报错，似乎是写反了？
![image](https://user-images.githubusercontent.com/29463605/70694581-f2da0e80-1cfa-11ea-9098-a3da4267c7d5.png)

**Comment by befinal** [comment]
没有错应该
