### ISSUE TITLE
支付验证签名失败

### ISSUE THREAD

**Issue by chenkang084** [befinal/node-tenpay#105]
使用api.unifiedOrder可以正确返回`prepay_id`等信息。然后调用`{
      timeStamp: `${new Date().getTime()}`,
      nonceStr: data.nonce_str,
      package: `prepay_id=${data.prepay_id}`,
      signType: 'MD5',
      paySign: data.sign
    }`，一直显示`支付验证签名失败`
求作者指导一下，非常感谢

**Comment by chenkang084** [comment]
这个问题我解决了。原因是微信支付需要二次签名。需要调用`_getSign`方法对`unifiedOrder`的返回结果进行二次签名。希望我的解决方法对其他有人有帮助。

**Comment by befinal** [comment]
有一个参数包装方法getPayParams，使用前下看下文档，花不了多少时间
