### ISSUE TITLE
请问有考虑加入小程序登陆换取openid功能吗

### ISSUE THREAD

**Issue by lizeyue326** [befinal/node-tenpay#108]
谢谢老哥把这么好的东西开源😁

**Comment by befinal** [comment]
这个只是支付相关的API
如果需要小程序code换openid的话, 可以自己写一个 其实挺简单的
参考  https://github.com/XL/wxapp-oauth

上边这个库里包含了code换取openid, 还有敏感数据的解密相关的API, 但是库没发布, 你可以参考一下

**Comment by lizeyue326** [comment]
好的 谢谢啦
