### ISSUE TITLE
退款时 无法获取具体错误

### ISSUE THREAD

**Issue by xream** [befinal/node-tenpay#112]
退款时, `type: 'refund'`, `err_code: 'ERROR'`

在 https://github.com/befinal/node-tenpay/blob/0729ebb018b620d64d2b5dde203843546c9f8beb/lib/index.js#L98

等于执行了 `throw new Error('ERROR')` 无法获取具体错误

**Comment by befinal** [comment]
加入debug看一下输出，是不是证书问题

**Comment by xream** [comment]
如截图所示 `err_code` 为 `'ERROR'`, 所以无法获取具体错误, 只能得到 `ERROR`

![image](https://user-images.githubusercontent.com/1210282/91122933-26649980-e6ce-11ea-8a35-34e5a1b0a2ef.png)

**Comment by befinal** [comment]
ok 稍后处理一下，好像是协议有变化了

**Comment by tclinhan** [comment]
怎么处理呢？遇到同样的问题

**Comment by Richar-Dada** [comment]
怎么解决 我也遇到了

**Comment by tsurumure** [comment]
![image](https://user-images.githubusercontent.com/519273/114960220-2bfb3380-9e99-11eb-8eaa-2bfceebf0036.png)
这个报错是什么问题？

**Comment by tsurumure** [comment]
![image](https://user-images.githubusercontent.com/519273/114960336-66fd6700-9e99-11eb-892d-cc61d53998cd.png)
这个报错是什么问题？

**Comment by tsurumure** [comment]
已解决了。自己回答自己，确实是证书的问题。载入证书是这样
```javascript
const pfx = fs.readFileSync(path.resolve('pay/apiclient_cert.p12'))   // 不要加 utf8
```

捕捉错误：
```javascript
await api.refund({
  ..
}).then(..).catch(e => {
  console.log(e)
  console.log(e.message)
})
```
