### ISSUE TITLE
发放代金券是微信支付代金券吗？还是商家券？

### ISSUE THREAD

**Issue by lyzhang1999** [befinal/node-tenpay#113]
微信支付代金券可以在用户使用微信支付的时候自动扣除，商家券是需要自己维护的。
不知道 sdk 的发券功能指的是发微信支付代金券吗？
api：https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/marketing/convention/chapter3_2.shtml

**Comment by qiyulan** [comment]
现在接口都是v2 的,v2只有代金券

**Comment by befinal** [comment]
v2接口微信代金券
