### ISSUE TITLE
请求错误

### ISSUE THREAD

**Issue by suedar** [befinal/node-tenpay#119]
<img width="585" alt="截屏2021-06-04 下午4 48 42" src="https://user-images.githubusercontent.com/18492953/120774520-f0a1ea80-c554-11eb-994d-e656203a7445.png">

提示 Error: PARAM_ERROR
有同学知道怎么解决吗

**Comment by befinal** [comment]
参数错误, 自己检查哪些参数是必须的

**Comment by suedar** [comment]
@befinal  有理 感谢
