### ISSUE TITLE
promise then 中rs 是不是不需要在判断  return_code，result_code的状态了。

### ISSUE THREAD

**Issue by cnn007** [befinal/node-tenpay#12]
` // 申请退款
        await api.refund(refund_order).then(rs => {
            // console.log('>>>>>>退款结果 result is :', JSON.stringify(rs))
            if (rs.return_code == 'SUCCESS' && rs.result_code == 'SUCCESS') {
                // 获取之前充值押金的的价格
                const refund_data = {
                    user_id: user_id,
                    wallet_id: wallet_id,
                    out_trade_no: out_trade_no,
                    out_refund_no: out_refund_no,
                    reason: reason,
                    refund_price: order.finally_price
                }
                console.log('>>>>>>退款结果1 result is :', JSON.stringify(rs))
                // 退款表
                return WalletDepositRefundModel.create(refund_data)
            } }).catch(err => {
            // 日志
            console.log('>>>>>>退款结果3 result is :', JSON.stringify(err))
        })`

谢谢楼主分享，现在有个小疑问是不是then里面不需要判断 return_code，result_code的状态，都是SUCCESS，所有的错误都在 catch 里面捕捉了。我看了util.js 里面的validate方法，好像需要return_code，result_code 都是SUCCESS才是正确的。我测试了一下也是这样，再来确认下。

**Comment by befinal** [comment]
是的，做了返回值校验，非正常返回或返回非成功消息均由catch处理
