### ISSUE TITLE
退款通知，现在支持吗

### ISSUE THREAD

**Issue by cnn007** [befinal/node-tenpay#13]
谢谢分享，请问现在支持退款通知吗，和支付通知的配置一样吗。
提供部分退款通知消息解密的方法。
`// xml 解析
var parseXML = function (xml, callback) {
    xml2js.parseString(xml, {
        trim: true,
        explicitArray: false
    }, function (err, result) {
        err ? callback(err) : callback(null, result ? result.root : {});
    });
};

// 解密
var decrypt = function (text, trade_type) {
    var result = '';
    if (trade_type == 'APP') {
        let key1 = CryptoJS.MD5(partner_key);
        result = CryptoJS.AES.decrypt(text, CryptoJS.enc.Utf8.parse(key1), {
            mode: CryptoJS.mode.ECB
        });
    }
    return result.toString(CryptoJS.enc.Utf8);
};`

**Comment by befinal** [comment]
正在准备加入，可能要晚点时间。
