### ISSUE TITLE
_getPayParams 中为什么返回了timeStamp与timestamp 俩个值一样的参数，timestamp有何用？ 

### ISSUE THREAD

**Issue by xb594328980** [befinal/node-tenpay#15]
// JSSDK支付签名(原始方法)
Payment.prototype._getPayParams = function(params, callback) {
	var that = this;
	that.unifiedOrder(params, function(err, result) {
		if (err) return callback(err);
		var pkg = Object.assign({}, {
			appId: that.appid,
			timeStamp: '' + (Date.now() / 1000 |0),
			nonceStr: util.generateNonceStr(),
			package: 'prepay_id=' + result.prepay_id,
			signType: 'MD5'
		});
		pkg.paySign = that.getSign(pkg);
		pkg.timestamp = pkg.timeStamp;
		callback(null, pkg);
	})
};

**Comment by befinal** [comment]
为了兼容老版微信网页jssdk

**Comment by xb594328980** [comment]
哦 哦， 谢谢，我说看到最新的jssdk中只有一个timeStamp的参数！
