### ISSUE TITLE
api.refund()调用的时候报签名错误

### ISSUE THREAD

**Issue by sunzhijian1982** [befinal/node-tenpay#17]
api.refund()调用的时候会报错“sign签名错误”，但是在微信退款查询里发现，刚才的退款已经成功了。

**Comment by sunzhijian1982** [comment]
nodejs里面调用的时候直接这么写可以么？
 api.refund(order).then(function (data) {
      console.log('11'+data);
      return response.success('data:'+data);
    })
      .catch(error => {
        console.error(error);
        response.error(error);
      });

**Comment by befinal** [comment]
问题已修复了, 是因为微信多返回了一个refund_channel字段是空字符串, 被带入了sign计算.

可以使用callback, promise, co, await/async等方式进行调用, response.success方法并没有实现, 如果是消息通知, 直接res.end('')应该就可以, 后续微信变化之后会进行更新

**Comment by sunzhijian1982** [comment]
不好意思，请问一下promise调用应该怎么写啊？刚接触nodejs，还没弄懂。能给写一个promise的调用看看么？

**Comment by sunzhijian1982** [comment]
不使用co和Koa，只用promise调用

**Comment by befinal** [comment]
你上边那个then写法就是promise
