### ISSUE TITLE
想请教下楼主，退款通知的解密怎么操作的～

### ISSUE THREAD

**Issue by RuiZhuo** [befinal/node-tenpay#19]
有没有事例代码，解密一直不正确

**Comment by befinal** [comment]
暂时没加入退款通知功能

**Comment by cnn007** [comment]
@RuiZhuo  看下 #13，部分解密代码，微信的步骤是错的。

**Comment by befinal** [comment]
看一下es6分支的代码，已经加入退款通知功能，文档和测试进行中，稍后会发布一个新版本，仅支持node 8以上版本

**Comment by befinal** [comment]
2.x版本已支持退款通知.
npm i tenpay@latest
