### ISSUE TITLE
关于app类型的支付

### ISSUE THREAD

**Issue by lostpupil** [befinal/node-tenpay#2]
提问：这个支持APP类型的charge吗？然后里面的统一下单的接口没有timestamp好像。

**Comment by befinal** [comment]
自己传入trade_type: APP应该就可以, 统一下单对于WEB端和APP使用的是同一个接口

**Comment by lostpupil** [comment]
多谢。
如果是APP的话还需要自己重新签名一次。
上面那个js sdk的那个签名就不能重用了。
