### ISSUE TITLE
企业付款，报错 err:mchid不匹配，但是实际是成功的。

### ISSUE THREAD

**Issue by cnn007** [befinal/node-tenpay#20]
企业付款，接口报错 err:mchid不匹配，但是实际是成功的，楼主看下呢。

**Comment by befinal** [comment]
看一下版本

**Comment by cnn007** [comment]
"tenpay": {
      "version": "1.1.4",

**Comment by befinal** [comment]
更新版本看一下

**Comment by cnn007** [comment]
更新到了 1.1.8 还是不行，如果是bug，就比较危险了，用户提现成功，余额却没有减少。

**Comment by befinal** [comment]
@cnn007 已经修复这个问题了.
另外, 对于涉及资金增加减少类的api, 应该从数据层面做资金安全措施, 不要完全依靠api的执行结果, 因为除了库本身的bug, 还有网络超时等情况.
