### ISSUE TITLE
哥们，关于微信支付getAppParamsByPrepay function的错误

### ISSUE THREAD

**Issue by kiroChen** [befinal/node-tenpay#22]
getAppParamsByPrepay(params) {
    let pkg = {
      appid: this.appid,
      partnerid: this.mchid,
      prepayid: params.prepay_id,
      package: 'Sign=WXPay',
      nonceStr: util.generate(),
      timestamp: '' + (Date.now() / 1000 |0)
    };
    pkg.sign = this._getSign(pkg);
    return pkg;
  }

这里的nonceStr应该是noncestr。希望改正

**Comment by befinal** [comment]
@kiroChen 嗯, 已修复了, 感谢
