### ISSUE TITLE
交易过程中出错之后，直接throw了Error

### ISSUE THREAD

**Issue by sunzhijian1982** [befinal/node-tenpay#24]
if (json.return_code !== 'SUCCESS') throw new Error(json.return_msg || 'XMLDataError');
    if (type !== 'middleware_refund') {
      if (json.result_code !== 'SUCCESS') throw new Error(json.err_code || 'XMLDataError');
    }

代码里，交易过程中出错了之后，直接throw了Error，这样json里返回的微信返回却看不到了，是不是直接callback(null, json)返回就好呢，让大家自己来处理这些错误，因为有时候是想要记录这些错误并处理的

**Comment by befinal** [comment]
新版本统一使用try catch，如果用callback，查看1.x版本试试

**Comment by sunzhijian1982** [comment]
可能没明白我的意思，我是看现在的代码
if (json.return_code !== 'SUCCESS') throw new Error(json.return_msg || 'XMLDataError');
if (type !== 'middleware_refund') {
   if (json.result_code !== 'SUCCESS') throw new Error(json.err_code || 'XMLDataError');
}
不throw error 直接返回json呢，因为出错之后大家一般也是要记录出错原因，比如说errorCodeDes字段，直接将json返回，然后大家自己处理结果呢？

**Comment by befinal** [comment]
如果这样，所有人都要手动去判断json的return_code和result_code，如果你你需要记录错误，catch error 然后通过error.message去判断错误原因

**Comment by befinal** [comment]
最新版本不再支持callback形式了，如果使用callback，建议fork 1.1.自己改动下7
