### ISSUE TITLE
运行报错You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by zhanghjgnu** [befinal/node-tenpay#25]
npm run dev报以下错误:
Module parse failed: Unexpected token (196:6)
You may need an appropriate loader to handle this file type.
|   micropay(params) {
|     let pkg = {
|       ...params,
|       appid: this.appid,
|       mch_id: this.mchid,

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/page/reg_order_confirm.vue 33:19-36
 @ ./src/page/reg_order_confirm.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:

**Comment by befinal** [comment]
node版本需大于8.3.0
