### ISSUE TITLE
scene_id 的 200 金额限制单位是 分 而不是 元

### ISSUE THREAD

**Issue by airyland** [befinal/node-tenpay#27]
https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_4&index=3

官方文档并没有写清楚，但是测试时发送大于2元时就已经需要 scene_id 了，毕竟最大红包金额也只是 200 元。或者代码不需要做判断处理，调用时有传入参数则传到接口。

https://github.com/befinal/node-tenpay/blob/8542215738501a064bc05b6e663945043ff4895f/lib/index.js#L339-L354

另外错误判断只针对特定错误，导致其他出错情况下不会 throw error，比如后台没有配置

``` js
{
 "return_msg": "参数错误:该场景未开通，请登陆商户平台：产品中心-现金红包-产品设置-使用场景 进行开通",
  "result_code": "FAIL",
  "err_code": "PARAM_ERROR",
  "err_code_des": "参数错误:该场景未开通，请登陆商户平台：产品中心-现金红包-产品设置-使用场景 进行开通"
}
```

**Comment by befinal** [comment]
修改过了, 发布了一个新版本
微信的文档太坑了

**Comment by befinal** [comment]
场景未开通不会抛出错误吗？我看了看你那个错误格式，代码里应该会捕获才对。
