### ISSUE TITLE
Typescript支持

### ISSUE THREAD

**Issue by ipfans** [befinal/node-tenpay#28]
能否提供对应d.ts文件支持Typescript使用？

**Comment by befinal** [comment]
能否提交一个PR?

**Comment by wangshenzhen** [comment]
这个退款通知和支付通知，有没有更详细的说明

**Comment by befinal** [comment]
@wangshenzhen 需要如何详细的说明呢? 文档应该写的比较清楚了

**Comment by leosj** [comment]
Error: wrong tag, POST https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers -1 (connected: false, keepalive socket: false

**Comment by leosj** [comment]
证书不正确应该会报证书错误，但是这里说标签不对，有点搞不懂，求解

**Comment by befinal** [comment]
这个错误应该就是reques产生的， 或者把你的代码发一下

**Comment by leosj** [comment]
`
const config = {
			appid: settings.appid,
			mchid: settings.mchid,
			partnerKey: settings.partnerKey,
			pfx: fs.readFileSync(path.join(__dirname,'../../public' + settings.apiclient_cert)),
			spbill_create_ip: ctx.request.ip !== '::1' ? ctx.request.ip : '127.0.0.1'
		};
		const out_trade_no = moment().format('YYYYMMDDHHmmssSSSSSSSSS') + '00' + Math.floor(Math.random()*(9999999-1000000+1)+1000000);

		const api = tenpay.init(config);
		let draw_result = await api.transfers({
			partner_trade_no: out_trade_no,
			openid: wxaaccount.openid,
			amount: money * 100,
			desc: '提现',
			check_name: 'NO_CHECK'
		});
`

**Comment by leosj** [comment]
证书文件果然错了
