### ISSUE TITLE
关于沙盒（微信支付仿真测试系统）提供支持

### ISSUE THREAD

**Issue by xcyxiner** [befinal/node-tenpay#31]
* [支付验收指引](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1)
*  <b> 希望可以在 config 中支持 对 sandbox 的配置,具体参考上面链接， 不然npm 安装后使用沙盒测试还得改 代码 </b>

**Comment by befinal** [comment]
微信的沙盒测试文档实在是太乱了，曾经试图加过这个，最后不得不放弃了。
不过应该可以提供一个参数来修改一下url指向沙盒地址，再提供一个获取沙盒密钥的api不知道是不是能满足需求？

**Comment by xcyxiner** [comment]
* 支付宝的一个SDK，是通过 环境变量来控制的，比如 [https://github.com/Luncher/alipay/blob/master/src/index.js](https://github.com/Luncher/alipay/blob/master/src/index.js)

```
const isTest = process.env.NODE_ENV === 'test'
const GETWAY = isTest ? config.ALIPAY_DEV_GETWAY : config.ALIPAY_GETWAY
```

* PayPal的SDK调用这边是通过config中的model来控制  [https://github.com/paypal/PayPal-node-SDK](https://github.com/paypal/PayPal-node-SDK)

```
paypal.configure({
  'mode': 'sandbox', //sandbox or live
  'client_id': 'EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM',
  'client_secret': 'EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM'
});
```

* 沙盒秘钥这个api这个到没看到有其他的解决方案。。。这个README.md 里加点注释也行。。。微信官方 获取秘钥这个太坑了。

**Comment by befinal** [comment]
因为sandbox的getsignkey是个异步操作，就算直接在config中加一个参数，也需要异步执行一个getsignkey去配置给其他api使用

**Comment by xcyxiner** [comment]
* API验签密钥获取完全可以自己处理。。这个配置config的时候加的。。。没必要放到这个里面 sdk里。。微信这货不提供一个接口，只给个API有点坑。。。怎么获取的不重要。。谁让微信不提供。。自己动手丰衣足食。。没指望在SDK中解决这个。。
*  [微信支付开发之沙箱密钥步骤详解](http://www.php.cn/weixin-kaifa-361783.html)
* 如果没理解错，API验签密钥 (沙箱秘钥) 应该替换  微信支付安全密钥 
* 这样就剩下 URL中添加 sandboxnew 了。。这个才是SDK中应该解决的。。

```
const config = {
  appid: '公众号ID',
  mchid: '微信商户号',
  partnerKey: '微信支付安全密钥或者API验签密钥?',
  pfx: require('fs').readFileSync('证书文件路径'),
  notify_url: '支付回调网址',
  spbill_create_ip: 'IP地址'
};
```

**Comment by befinal** [comment]
增加了一个getSignkey方法来获取沙盒密钥.
添加了一个sandbox参数来开启沙盒模式:
```javascript
let sandboxAPI = new tenpay({
  ...config,
  partnerKey: sandbox_signkey,
  sandbox: true
});
```

**Comment by befinal** [comment]
let sandboxAPI = tenpay.sandbox(config);
