### ISSUE TITLE
付款通知接口

### ISSUE THREAD

**Issue by zhuyuejianke** [befinal/node-tenpay#35]
lib\index.js
`
switch (type) {
      case 'middleware_refund':
        if (json.appid !== this.appid) throw new Error('appid不匹配');
        if (json.mch_id !== this.mchid) throw new Error('mch_id不匹配');
        let key = util.md5(this.partnerKey).toLowerCase();
        let info = util.decrypt(json.req_info, key);
        json.req_info = await util.parseXML(info);
        break;
      case 'transfers':
        if (json.mchid !== this.mchid) throw new Error('mchid不匹配');
        break;
      case 'sendredpack':
      case 'sendgroupredpack':
        if (json.wxappid !== this.appid) throw new Error('wxappid不匹配');
        if (json.mch_id !== this.mchid) throw new Error('mchid不匹配');
        break;
      case 'gethbinfo':
      case 'gettransferinfo':
        if (json.mch_id !== this.mchid) throw new Error('mchid不匹配');
        break;
      default:
        if (json.appid !== this.appid) throw new Error('appid不匹配');
        if (json.mch_id !== this.mchid) throw new Error('mch_id不匹配');
        if (json.sign !== this._getSign(json)) throw new Error('sign签名错误');
    }
    return json;
`

微信官方都没有req_info 这个字段，带req_info 的这行代码报错，怎么回事？

**Comment by befinal** [comment]
这是退款通知接口里的, 不是付款通知的
