### ISSUE TITLE
支付通知中间件

### ISSUE THREAD

**Issue by zhuyuejianke** [befinal/node-tenpay#36]
微信的文档说明：https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_7&index=8
微信支付通知xml数据中有个result_code字段为FAIL时，表示用户支付未成功。这个未成功的消息，业务服务器应该有权知道。

但是tenpay的支付通知中间件，在这种情况下会返回给微信支付服务器return res.reply('XMLDataError')，暗示业务服务器未收到消息，而不是收到消息。

总感觉这在逻辑上是错的。

**Comment by zhuyuejianke** [comment]
@befinal ，直接忽略也可以，但是我想微信服务器会认为消息未收到，会继续补充发若干次消息。另外，既然有debug选项，那么解析xml失败时（或者支付失败时）应该允许打印错误消息。

还有一个逻辑问题。中间件只有在成功解析xml并且result==success时才允许下一个中间件，比如控制器执行。那么既然已经支付成功了，钱也就是收到了，为什么还允许在控制器中使用res.replay("错误消息")呢？

`  // Koa中间件
  middleware(type = 'pay') {
    let that = this;
    return async (ctx, next) => {
      ctx.reply = msg => {
        ctx.type = 'application/xml; charset=utf-8';
        ctx.body = replyData(msg);
      }

      try {
        if (typeof ctx.request.body !== 'string') throw new Error('XMLDataError');
        ctx.request.weixin = await this._parse(ctx.request.body, 'middleware_' + type);
      } catch (err) {
        if(that.debug){console.log("_parse error:",err);}
        return ctx.reply('XMLDataError');
      }

      await next();
    };
  }
`

**Comment by befinal** [comment]
@zhuyuejianke ,  当时的设想是, debug是用于API的返回结果调试的, 不需要用于消息通知,
消息通知的消息体完全可以通过自己对request的入口来统一实现:
```javascript
app.use((req, res, next) => {
  console.log('\r\n==>', new Date().toLocaleString());
  console.log(req.method, req.url);
  if (req.method == 'POST') console.log('Data', req.body);
  next();
});
```

至于支付成功的消息通知里之所以没有做自动的reply, 而是让用户自己使用reply, 至于用户是直接reply成功还是reply失败, 那么根据业务逻辑自己处理就可以了.

在遇到业务逻辑中依赖其它远程服务(比如数据库连接中断, 其它第三方API之类的)但是服务不可用的时候, 可以reply失败可以让微信过一会重发一次.

**Comment by befinal** [comment]
之前对业务逻辑的理解应该是微信方面发过来的消息必须是支付成功, 这样才需要业务内对该支付消息对应的支付单做处理, 如果微信发过来的消息格式错误或者不是支付成功, 那么这个消息就直接扔掉.
实际使用中其实并没有遇到微信发过来的消息格式错误或者result_code是fail的情况.

**Comment by zhuyuejianke** [comment]
好的
