### ISSUE TITLE
body使用中文时签名错误

### ISSUE THREAD

**Issue by newbyebye** [befinal/node-tenpay#4]
在计算字符串md5时需要指定编码为utf8
Payment.prototype.getSign = function(pkg) {
	pkg = Object.assign({}, pkg);
	delete pkg.sign;
	var str = ulits.toQueryString(pkg) + '&key=' + this.partnerKey;
	return crypto.createHash('md5').update(str, '**utf8**').digest('hex').toUpperCase();
};

**Comment by befinal** [comment]
稍后测试一下会修复，感谢反馈
