### ISSUE TITLE
调用api.refund 接口

### ISSUE THREAD

**Issue by yuyuabc1** [befinal/node-tenpay#40]
api.refund({
      out_trade_no: order._id,
      out_refund_no: refund._id,
      total_fee: 1,
      refund_fee: 1
    })
//值都是正确的
报错
server error { AssertionError [ERR_ASSERTION]: invalid status code: -1
    at Object.set status [as status] (D:\document\takeout-api\node_modules\koa\lib\response.js:86:5)
    at Object.status (D:\document\takeout-api\node_modules\delegates\index.js:92:31)
    at D:\document\takeout-api\middlewares\error-handling.js:9:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '==' } { request:
   { method: 'POST',
     url: '/order/cancel',
     header:
      { host: 'localhost:4000',
        connection: 'keep-alive',
        'content-length': '33',
        pragma: 'no-cache',
        'cache-control': 'no-cache',
        'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 wechatdevtools/1.02.1806120 MicroMessenger/6.5.7 Language/zh_CN webview/',
        origin: 'http://127.0.0.1:26462',
        authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiU3N2ZnhpbmRHZWtITXM4cVVQZit2QT09IiwiaWF0IjoxNTI5MDI3NTk0LCJleHAiOjE1MjkyODY3OTR9.Zx7r9-2RQXC02IWsWYiFSh6V4uV243U5xfJvKcQa-zM',
        'content-type': 'application/json; charset=UTF-8',
        accept: '*/*',
        referer: 'https://servicewechat.com/wx67518436f322a9c4/devtools/page-frame.html',
        'accept-encoding': 'gzip, deflate, br' } },
  response:
   { status: 404,
     message: 'Not Found',
     header:
      { 'x-dns-prefetch-control': 'off',
        'x-frame-options': 'SAMEORIGIN',
        'strict-transport-security': 'max-age=15552000; includeSubDomains',
        'x-download-options': 'noopen',
        'x-content-type-options': 'nosniff',
        'x-xss-protection': '1; mode=block',
        vary: 'Origin',
        'access-control-allow-origin': 'http://127.0.0.1:26462' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/order/cancel',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

**Comment by befinal** [comment]
检查证书
