### ISSUE TITLE
能够支持EGG吗

### ISSUE THREAD

**Issue by fishlao** [befinal/node-tenpay#44]

**Comment by befinal** [comment]
没有计划直接做成egg中间件

**Comment by befinal** [comment]
你可以试一下吧，我们这边没有使用egg。

**Comment by songzhengxu** [comment]
只是没有封装中间件而已， 也可以直接用的， 我现在就是直接在用

**Comment by shellteo** [comment]
> 只是没有封装中间件而已， 也可以直接用的， 我现在就是直接在用

请问 微信消息通知 怎么在eggjs中使用的

**Comment by mani95lisa** [comment]
@fishlao @shellteo 使用方式如下

在配置里面加上
const bodyParserConfig = {
    enable: true,
    encoding: 'utf8',
    formLimit: '100kb',
    jsonLimit: '100kb',
    strict: true,
    queryString: {
      arrayLimit: 100,
      depth: 5,
      parameterLimit: 1000,
    },
    enableTypes: [ 'json', 'form', 'text' ],
    extendTypes: {
      text: [ 'text/xml', 'application/xml' ],
    },
  };
  // 覆盖egg自带的配置
  config.bodyParser = bodyParserConfig;

在路由上
router.post('/wechat/pay/notify', api.middleware('pay'), wechat.payNotify);

这样就可以了
