### ISSUE TITLE
最近微信支付暴露的XXE攻击，这个包有没有受到影响或者防范

### ISSUE THREAD

**Issue by jinjianhua727** [befinal/node-tenpay#47]
[微信官方的公告和建议](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5)

**Comment by zylibin** [comment]
不影响。底层sax-js忽略了自定义DTD。

参考链接：https://github.com/Leonidas-from-XIV/node-xml2js/issues/469
