### ISSUE TITLE
关于h5支付必需字段scene_info

### ISSUE THREAD

**Issue by Laumlin** [befinal/node-tenpay#53]
这边生成的是这样的
![image](https://user-images.githubusercontent.com/31385709/43062976-13d8faa4-8e8d-11e8-8d1c-e47b90145090.png)
而官网给出的是这样
<scene_info>{"h5_info": {"type":"IOS","app_name": "王者荣耀","package_name": "com.tencent.tmgp.sgame"}}</scene_info>
请问有什么解决的好办法吗？
谢谢！

**Comment by befinal** [comment]
scene_info内点数据用json.stringify处理下试试
