### ISSUE TITLE
请问这是什么错误？

### ISSUE THREAD

**Issue by linrx1511** [befinal/node-tenpay#54]
{"code":-1,"reason":"/data/release/node-weapp-demo/node_modules/tenpay/lib/index.js:52\n ...config,\n ^^^\n\nSyntaxError: Unexpected token ...\n at createScript (vm.js:74:10)\n at Object.runInThisContext (vm.js:"}

**Comment by befinal** [comment]
查看node版本是否大于8.3

**Comment by linrx1511** [comment]
谢谢，是这个原因

**Comment by linrx1511** [comment]
微信的开发环境不支持8.3以上的，只有8.2.1，所以没办调试，请问有办法解决吗

**Comment by befinal** [comment]
自己fork一下，把解构操作符用Object.assign替换掉

**Comment by linrx1511** [comment]
谢谢你
