### ISSUE TITLE
您好，没看到授权，组织包，计算签名那步呢？

### ISSUE THREAD

**Issue by lpp288** [befinal/node-tenpay#6]
您好，没看到授权，组织包，计算签名那步在哪呢

**Comment by befinal** [comment]
授权是什么？
组织包和计算签名在common.js下getSign方法

**Comment by lpp288** [comment]
看到了，那就是只要调用getPayParams，支付参数都有了，返给前端，前端就根据参数调起微信支付，支付完再提交到后端的notify_url修改订单状态，就可以了是吗？

**Comment by befinal** [comment]
是这样, getPayParams执行了微信的统一下单并自动生成了前端可用的支付参数, 直接返回给前端就可以调起支付

**Comment by lpp288** [comment]
发现一个问题呀，微信appid 和商户号mch_id必须一致？在一个公众号下，可以支付到其他商户啊

**Comment by befinal** [comment]
这个去看微信文档吧
