### ISSUE TITLE
缺时间戳

### ISSUE THREAD

**Issue by kevin1942** [befinal/node-tenpay#60]
使用统一下单接口以后，	let result = await api.unifiedOrder ,返回值里面缺少时间戳 timeStamp，但是返回值sign加密是包含了时间戳的吧。没办法只有，前台获取了时间戳填入，却验证不通过
function onBridgeReady(){
   WeixinJSBridge.invoke(
      'getBrandWCPayRequest', {
         "appId":"wx2421b1c4370ec43b",     //公众号名称，由商户传入     
         "timeStamp":"1395712654",         //时间戳，自1970年以来的秒数     
         "nonceStr":"e61463f8efa94090b1f366cccfbbb444", //随机串     
         "package":"prepay_id=u802345jgfjsdfgsdg888",     
         "signType":"MD5",         //微信签名方式：     
         "paySign":"70EA570631E4BB79628FBCA90534C63FF7FADD89" //微信签名 
      },
      function(res){
      if(res.err_msg == "get_brand_wcpay_request:ok" ){
      // 使用以上方式判断前端返回,微信团队郑重提示：
            //res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
      } 
   }); 
}

**Comment by kevin1942** [comment]
我的处理办法就是在前台重新加密 使用sign,很抱歉，是不是我用错了呢

**Comment by befinal** [comment]
直接使用getPayParams就可以 不用自己调用统一下单
