### ISSUE TITLE
如何获得openid和unionid呢？

### ISSUE THREAD

**Issue by xeoshow** [befinal/node-tenpay#65]
是否有这样接口？谢谢！

**Comment by befinal** [comment]
根据不同场景可以使用其它库 如wechat-api或co-wechat-api

**Comment by xeoshow** [comment]
百度和google，也在https://www.npmjs.com/找了，没看到所说的wechat-api或co-wechat-api，麻烦能贴个链接吗？谢谢！

**Comment by befinal** [comment]
https://github.com/node-webot/wechat-api
https://github.com/node-webot/co-wechat-api

**Comment by xeoshow** [comment]
感谢感谢！

**Comment by xeoshow** [comment]
@befinal 麻烦再请问下：这个模块有qq群或相关讨论的地方吗？再次感谢。

**Comment by befinal** [comment]
可以进这个qq群
欢迎加入node-wechat模块开发群，群聊号码：157964097

**Comment by xeoshow** [comment]
已加入，谢谢
