### ISSUE TITLE
服务商统一下单怎么调用？

### ISSUE THREAD

**Issue by linrx1511** [befinal/node-tenpay#71]
请问一下服务商统一下单怎么调用？返回 普通商户不允许传sub_mch_id

api.getPayParams({
        sub_appid: '',  //小程序APPID
        sub_mch_id: '',         //特约商户号
        sub_openid: openid,               //openid
        out_trade_no: tradeNum,
        body: body,
        total_fee: total_fee,
      })

**Comment by befinal** [comment]
确认使用的主商户号是服务商吗?

**Comment by linrx1511** [comment]
不好意思 ，是我搞混，就这样调用就可以了，谢谢。
