### ISSUE TITLE
成功返回信息格式不对

### ISSUE THREAD

**Issue by SealedLove** [befinal/node-tenpay#72]
const replyData = msg => util.buildXML(msg ? {return_code: 'FAIL', return_msg: msg} : {return_code: 'SUCCESS'});

微信支付最新的成功返回消息格式：{return_code: 'SUCCESS', return_msg: 'OK'}

另外咨询一下 为什么支付成功回调中回req.body获取的到内容是空的？

**Comment by befinal** [comment]
使用app.use('url', bodyParser.text({type: '/xml'}))对指定路由使用中间件
或者使用你们自己的解析方法把xml内容写入到req.body中

**Comment by SealedLove** [comment]
感谢大神及时的指导
