### ISSUE TITLE
H5支付时调用统一下单接口报告INVALID_REQUEST错误!

### ISSUE THREAD

**Issue by run27017** [befinal/node-tenpay#73]
```js
api.unifiedOrder({
  out_trade_no: '143254432432',
  body: '商品简单描述',
  total_fee: '99',
  openid: config.wx.testOpenId,
  trade_type: 'MWEB'
}).then(result => {
  console.log('result', result)
}).catch(function () {
  console.error(arguments)
});
```

如上，如果trade_type是JSAPI，则返回成功。如果trade_type是MWEB，则catch到INVALID_REQUEST错误，但却得不到任何补充的信息了。这个INVALID_REQUEST是微信的返回结果，还是发送前拦截的结果。我想知道微信返回给我什么该怎么办？

详细错误如下（很简单）：

```js
{ '0': Error: INVALID_REQUEST
    at Payment._parse (/home/hello/workspace/maikeji_xcx_demo/xcx_pays/node_modules/tenpay/lib/index.js:97:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) }
```

**Comment by run27017** [comment]
补充一下，我知道错误原因了。只需要在`tenpay/lib/index.js`下添加一行console.log，就可以拿到微信端返回的错误结果了？希望后续不要压制微信端的返回结果，这样不利于自己调试错误。

（我看了源码，貌似是把所有的错误都压缩成了一个INVALID_REQUEST异常）

**Comment by befinal** [comment]
调试可以使用debug模式, 正常参数无错, 证书正确的情况下, 不会出现未知错误.

**Comment by run27017** [comment]
收到，确实debug设为true就可以了。建议debug模式在文档的显著位置标明，或者catch部分的error增加个字段details，指明微信端返回的错误。这样都好，不会影响到性能的，望知悉。

**Comment by befinal** [comment]
嗯, 在考虑怎么样处理错误会更友好一点, 还没有找到更好的方法.

**Comment by run27017** [comment]
@befinal 其实也很简单，只需要在每个构建的错误里加上一个字段`wxOriginalBody`（微信原生返回），它是一个字符串类型就可以了。

微信原生返回的东西还是有用的，有时候从原生返回的内容（json或者xml也好）提取出信息，丢到google一搜，还是能搜出很多答案了。这样也就会少了很多不必要的issue了。

另外一个建议是，可以将常见的错误原因也随异常一起返回。例如#37的问题，调用refund接口常见的错误`socket hang up`情况，可以提示一下“可能是证书没有配置或配置异常"。当然了，如果这样做较繁琐倒也不必要了，通过搜索issue也是能得到答案的。
