### ISSUE TITLE
申请退款报错

### ISSUE THREAD

**Issue by songzhengxu** [befinal/node-tenpay#77]
沙箱环境，，根据文档验证接口， ，下单和查询可用， 退款接口报错，提示

`
not enough data, POST https://api.mch.weixin.qq.com/sandboxnew/secapi/pay/refund -1 (connected: false, keepalive socket: false, socketHandledRequests: 0, socketHandledResponses: 0)
`

把生成的参数 拿到postMan中测试，可以连通接口， ，

**Comment by befinal** [comment]
检查下证书配置是否正确

**Comment by songzhengxu** [comment]
证书配置是正确的，，而且正式环境也在正常下单支付， 小程序和公众号都在使用， 今天开发退款功能，遇到问题，都是报这个错误

**Comment by befinal** [comment]
正式环境的退款出现问题了吗?

**Comment by ilaipi** [comment]
找到原因了吗？

**Comment by ilaipi** [comment]
我这边是证书没配置，配置证书之后就可以了。

（之前只是调用统一下单接口，不需要证书，以为已经配好了，实际上没有配置）
