### ISSUE TITLE
返回 err_code_des

### ISSUE THREAD

**Issue by hehex9** [befinal/node-tenpay#78]
err_code 和 err_code_des 应该都提供给调用方。
现在的逻辑似乎是：
```javascript
if (json.result_code !== 'SUCCESS') throw new Error(json.err_code || 'XMLDataError')
```
无法获得 err_code_des 等信息

**Comment by befinal** [comment]
通过err_code可以处理生产环境的业务逻辑
如果需要在开发过程中查看err_code_dec, 使用debug模式就行

let api = new tenpay(config, true);

**Comment by hehex9** [comment]
好的，谢谢
