### ISSUE TITLE
您好，支付回调完，res.reply(''); 这个方没效果呢？

### ISSUE THREAD

**Issue by lpp288** [befinal/node-tenpay#8]
res.reply('success');
res.reply('fail');
都不行，微信还是会不停的回调过来

**Comment by befinal** [comment]
其实直接使用res.end('success')随便回复微信服务器一下就可以, 微信方其实并没有完全按照文档要求的回复格式进行处理. 所以暂时没有对这个进行非常规范的处理, 当前测试没有什么问题, 后期可能会完善一下增加一个res.success()和res.fail()方法来处理.

**Comment by befinal** [comment]
另外建议自己这边对订单进行一个排重的操作处理, 因为就算完全按照微信文档进行回复, 也不能保证微信一个订单真的只发送一次(网络超时等因素), 所以还是需要自己在业务逻辑上进行验证, 避免一个订单被多次处理.

**Comment by lpp288** [comment]
谢谢指导
