### ISSUE TITLE
服务商下的APP支付参数

### ISSUE THREAD

**Issue by lumiasaki** [befinal/node-tenpay#81]
在使用APP支付时，调用`getAppParams()`发现其中的appid和partnerid都是取的this中初始化时的值，而初始化时使用的值是服务商的，在`getAppParams()`调用时应该使用**子商户的appid和子商户号**，否则会出现`支付验证签名失败`。

请问这是一个issue吗？还是我使用方法不正确？

如下代码展示了我有疑问的部分，注释中标注了我认为有问题的两个字段，这里是否需要增加对服务商模式下的支持？

```javascript
// 获取APP支付参数(通过预支付会话标志)
  getAppParamsByPrepay(params, signType) {
    let pkg = {
      appid: this.appid,   // 改为sub_appid的值可在服务商模式下，子商户调用成功
      partnerid: this.mchid,  // 改为sub_mch_id的值可在服务商模式下，子商户调用成功
      prepayid: params.prepay_id,
      package: 'Sign=WXPay',
      noncestr: util.generate(),
      timestamp: '' + (Date.now() / 1000 |0)
    };
    pkg.sign = this._getSign(pkg, signType);
    return pkg;
  }
```

**Comment by befinal** [comment]
嗯, 这是一个bug, 应该是和JSAPI支付一样的, 需要覆盖appid和partnerid参数

**Comment by befinal** [comment]
更新了一下版本了.
`javascript
let params = api.getAppParamsByPrepay({
  sub_appid: 'xxx',
  sub_mch_id: 'xxx',
  prepay_id: 'xxx'
}, 'MD5');
`

**Comment by lumiasaki** [comment]
@befinal 好的，非常感谢！
