### ISSUE TITLE
请问H5支付下单,是调用api.getPayParams这个接口吗,trade_type参数应该如何填写?

### ISSUE THREAD

**Issue by 119992278** [befinal/node-tenpay#83]
请问H5支付下单,是调用api.getPayParams这个接口吗,trade_type参数应该如何填写?

**Comment by befinal** [comment]
H5支付trade_type为MWEB, 调用统一下单API, 会直接返回mweb_url

[https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=15_3](微信支付H5支付)

**Comment by 119992278** [comment]
"调用统一下单API, 会直接返回mweb_url" 这句话意思是?

**Comment by befinal** [comment]
mweb_url直接在移动端浏览器打开可以调起微信客户端进行支付
