### ISSUE TITLE
要不要支持一波合单支付

### ISSUE THREAD

**Issue by WuHanMuMu** [befinal/node-tenpay#84]

**Comment by befinal** [comment]
合单支付需要额外的权限吗？

**Comment by WuHanMuMu** [comment]
https://pay.weixin.qq.com/wiki/doc/api/combine.php?chapter=24_1&index=2 
不需要

**Comment by befinal** [comment]
好的，稍后看一下，如果需要额外权限就没办法测试了

**Comment by befinal** [comment]
@WuHanMuMu 合单支付好像需要额外的权限, 测试了一下返回NOAUTH
