### ISSUE TITLE
 获取APP支付参数，换一个端口后App支付提示“支付验证签名失败”，换回来OK了

### ISSUE THREAD

**Issue by lesany** [befinal/node-tenpay#88]

**Comment by lesany** [comment]
这个是什么问题引起的，大家怎么解决的？

**Comment by befinal** [comment]
换端口是什么意思？

**Comment by lesany** [comment]
例如 ：
 online 目录 node 监听的是8001 作为一个生产版本，APP支付调试测试OK,

本机的 beta目录 git 同样的代码作为一个开发版本，node 监听 8002，App 支付就会提示 “支付验证签名失败”

**Comment by befinal** [comment]
检查config看看生产和开发环境的区别然后再排错

**Comment by lesany** [comment]
好的，谢谢，麻烦了哈
