### ISSUE TITLE
退款接口不能使用，请问是什么原因呢。

### ISSUE THREAD

**Issue by x-da** [befinal/node-tenpay#93]
![image](https://user-images.githubusercontent.com/7136286/58781505-a48ed900-860e-11e9-9273-053aceab9a66.png)

代码段：
![image](https://user-images.githubusercontent.com/7136286/58781529-bff9e400-860e-11e9-8ed9-93d7b67c594a.png)

支付功能又是正常的，能正常支付成功。

**Comment by befinal** [comment]
检查证书配置

**Comment by befinal** [comment]
你这代码里的证书用法不对, 看下readme吧

如业务流程中用到含证书请求的API, 则必须在初始时传入pfx参数

**Comment by x-da** [comment]
好的，我看看，感谢。
