### ISSUE TITLE
返回的数据格式和微信官方提供的不一致？

### ISSUE THREAD

**Issue by changegogo** [befinal/node-tenpay#97]
tenpay返回的
<?xml version="1.0"?>
<xml>
    <return_code>SUCCESS</return_code>
</xml>
微信官方要求的：
<xml>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <return_msg><![CDATA[OK]]></return_msg>
</xml>

**Comment by changegogo** [comment]
缺少![CDATA

**Comment by befinal** [comment]
这个现在应该并没有影响, 在没有影响的原则下不做改动
